version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=products
      - POSTGRES_USER=brian
      - POSTGRES_PASSWORD=admin
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - SWAGGER_JSON=/api-docs/swagger.json
    ports:
      - '8080:8080'
    volumes:
      - ./swagger:/api-docs
